---
name: Terraform Apply on Azure
run-name: ${{ github.actor }} is deploying Azure
on: push
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  Deploy-Azure:
    runs-on: ubuntu-latest
    steps:
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      - name: Terraform Init
        working-directory: ./azure
        run: |+
          terraform init
          terraform apply -auto-approve
          echo $(terraform output -raw public_ip_address) > instance-ips-az.txt 
            
